### ISSUE TITLE
Can't Log In After Redeploying on OpenShift - KDF Config is Required

### ISSUE THREAD

**Issue by omnibaer** [bitwarden/clients#15121]
### Steps To Reproduce

1. Go to bitwarden web page (established via OpenShift route: https://bitwarden.apps.oc... <domain removed>)
2. Enter email and password. Click on Log In with Master Password

### Expected Result

Login should proceed normally

### Actual Result

Error appears in top right corner pop-up: KDF Config is Required

### Screenshots or Videos

![Image](https://github.com/user-attachments/assets/375dc60e-2227-4a52-8a4f-3395fb6f3f44)

### Additional Context

Previous Bitwarden instance crashed with OpenShift cluster. When recreating, managed to migrate all 6 PVCs without issues, but had to reaccomplish helm charts. Bitwarden updated to latest (2025.5.0) as shown in screenshot. Possible that values were missing in my-values.yaml that configured KDF?

### Operating System

Linux

### Operating System Version

AlmaLinux 8.10, OKD 4.20.0-okd-scos.ec.2

### Web Browser

Firefox

### Browser Version

139.0.1

### Build Version

2025.5.0

### Issue Tracking Info

- [x] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Neonwarden** [comment]
Hi there,

This has been escalated for further investigation. If you have more information that can help us, please add it below. 

Thanks!

**Comment by omnibaer** [comment]
Good morning,

Attempted a fresh deployment with the below my-values.yaml and custom secret (all obfuscated, of course), I still get the above KDF error. Also notably I had to change the MSSQL image, "mcr.microsoft.com/mssql/server:2022-CU11-ubuntu-22.04" wasn't starting up, citing an error 22. Using 2022-latest fixes the problem, though I had to change the startup probe to point to mssql-tools18 instead of -tools.
bw-secret:
```
oc create secret generic custom-secret -n bitwarden \
    --from-literal=globalSettings__installation__id="<UUID>" \
    --from-literal=globalSettings__installation__key="<KEY ENTERED>" \
    --from-literal=globalSettings__mail__smtp__username="<USERNAME>" \
    --from-literal=globalSettings__mail__smtp__password="<PASSWORD>" \
    --from-literal=globalSettings__yubico__clientId="REPLACE" \
    --from-literal=globalSettings__yubico__key="REPLACE" \
    --from-literal=globalSettings__hibpApiKey="REPLACE" \
    --from-literal=SA_PASSWORD="<SA PASSWORD>"
```
my-values:
```
# Optional - Override the chart name if desired
fullnameOverride: ""
nameOverride: ""

general:
  # Domain name for the service
  domain: "<MY FQDN>"
  ingress:
    # Set to false if using a custom ingress
    enabled: false
    # Current supported values for ingress type include: nginx
    className: "nginx"
     ## - Annotations to add to the Ingress resource.
    annotations:
      # nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      # nginx.ingress.kubernetes.io/use-regex: "true"
      # nginx.ingress.kubernetes.io/rewrite-target: /$1
      # nginx.ingress.kubernetes.io/proxy-body-size: 500m
      # nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
      # nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
      # nginx.ingress.kubernetes.io/proxy-connect-timeout: "600"
    ## - Labels to add to the Ingress resource
    labels: {}
    # Certificate options
    tls:
      # TLS certificate secret name
      name:
      # Cluster cert issuer (ex. Let's Encrypt) name if one exists
      clusterIssuer:
    # Ingress path configuration - The samples provided are for Nginx. Examples with other Ingress providers are in the chart Readme on GitHub
    paths:
      web:
        path: /(.*)
        pathType: ImplementationSpecific
      attachments:
        path: /attachments/(.*)
        pathType: ImplementationSpecific
      api:
        path: /api/(.*)
        pathType: ImplementationSpecific
      icons:
        path: /icons/(.*)
        pathType: ImplementationSpecific
      notifications:
        path: /notifications/(.*)
        pathType: ImplementationSpecific
      events:
        path: /events/(.*)
        pathType: ImplementationSpecific
      scim:
        path: /scim/(.*)
        pathType: ImplementationSpecific
      sso:
        path: /(sso/.*)
        pathType: ImplementationSpecific
      identity:
        path: /(identity/.*)
        pathType: ImplementationSpecific
      admin:
        path: /(admin/?.*)
        pathType: ImplementationSpecific

  # Override application container version tags.  Theses will be versioned with the chart and need not be changed in most circumstances.
  coreVersionOverride: ""
  webVersionOverride: ""
  # Disable account registration on web vault
  disableUserRegistration: "false"
  # Comma-separated list of email addresses for Admin users
  admins: "false"
  email:
    # Email address used for invitations, typically no-reply@smtp-host
    replyToEmail: "omnibaer1@gmail.com"
    # Your SMTP server hostname (recommended) or IP address
    smtpHost: "smtp.gmail.com"
    # The SMTP port used by the SMTP server
    smtpPort: "587"
    # Whether your SMTP server uses an encryption protocol, "true" for SSL, "false" for TLS
    smtpSsl: "false"
    # Specify true to explicitly trust the certificate presented by the SMTP server (not recommended for production).
    smtpTrustServer: "false"
    # Specify true to use SSL (not TLS) on port 25.
    smtpSslOverride: "false"
    # Specify true to force STARTTLS (Opportunistic TLS).
    smtpStartTls: "false"
  # Custom labels to add throughout the installation
  labels: {}
  # Specifies the access mode for persistent volume claims.  This should not be changed in most cases, and the allowable
  # values are only ReadWriteMany and ReadWriteOnce.  Please read https://kubernetes.io/docs/concepts/storage/persistent-volumes/#access-modes
  # to better understand these options before changing this value.
  volumeAccessMode: "ReadWriteMany"
  # Set to true to allow communication between your server and our cloud system. Doing so enables billing and license sync.  Please see: https://bitwarden.com/help/self-host-an-organization/#step-4-setup-billing-and-license-sync
  enableCloudCommunication: false
  # Cloud region for sync.  Please see: https://bitwarden.com/help/families-for-enterprise-self-hosted/#step-1-enable-cloud-communication
  cloudRegion: US

# Specify the name of the shared storage class
# This storage class requires ReadWriteMany.  You will need to provide your own storage class.  Storage classes with automatic volume previsioners are recommended.
sharedStorageClassName: "shared-storage"

# Secrets are required.  Review the chart README on GitHub for details on creating these secrets
secrets:
  secretName: custom-secret
  # Secrets can either be created via 'kubectl create secrets' or by using a secret provider class.  If using the latter, specify the name here
  secretProviderClass:

# Settings for individual service containers
component:
  # The Admin component
  admin:
    # Additional deployment labels
    labels: {}
    # Image name, tag, and pull policy
    image:
      name: ghcr.io/bitwarden/admin
    # The pod resource requirements.  You can adjust these up and down for your environment
    resources:
      requests:
        memory: "64Mi"
        cpu: "50m"
      limits:
        memory: "128Mi"
        cpu: "100m"
    # Specifies the strategy used to replace old Pods by new ones. The value can be "Recreate" or "RollingUpdate". "RollingUpdate" is the default value.
    deploymentStrategy: RollingUpdate
    # This will set the Kubernetes container security context
    securityContext:
    # Run the pod under a service account you create.  This is especially useful for OpenShift deployments
    podServiceAccount: bitwarden-sa
  api:
    # Additional deployment labels
    labels: {}
    # Image name, tag, and pull policy
    image:
      name: ghcr.io/bitwarden/api
    # The pod resource requirements.  You can adjust these up and down for your environment
    resources:
      requests:
        memory: "128Mi"
        cpu: "100m"
      limits:
        memory: "256Mi"
        cpu: "200m"
    # Specifies the strategy used to replace old Pods by new ones. The value can be "Recreate" or "RollingUpdate". "RollingUpdate" is the default value.
    deploymentStrategy: RollingUpdate
    # This will set the Kubernetes container security context
    securityContext:
    # Run the pod under a service account you create.  This is especially useful for OpenShift deployments
    podServiceAccount: bitwarden-sa
  attachments:
    # Additional deployment labels
    labels: {}
    # Image name, tag, and pull policy
    image:
      name: ghcr.io/bitwarden/attachments
    # The pod resource requirements.  You can adjust these up and down for your environment
    resources:
      requests:
        memory: "64Mi"
        cpu: "50m"
      limits:
        memory: "128Mi"
        cpu: "100m"
    # Specifies the strategy used to replace old Pods by new ones. The value can be "Recreate" or "RollingUpdate". "RollingUpdate" is the default value.
    deploymentStrategy: RollingUpdate
    # This will set the Kubernetes container security context
    securityContext:
    # Run the pod under a service account you create.  This is especially useful for OpenShift deployments
    podServiceAccount: bitwarden-sa
  events:
    # Additional deployment labels
    labels: {}
    # Image name, tag, and pull policy
    image:
      name: ghcr.io/bitwarden/events
    # The pod resource requirements.  You can adjust these up and down for your environment
    resources:
      requests:
        memory: "64Mi"
        cpu: "50m"
      limits:
        memory: "128Mi"
        cpu: "100m"
    # Specifies the strategy used to replace old Pods by new ones. The value can be "Recreate" or "RollingUpdate". "RollingUpdate" is the default value.
    deploymentStrategy: RollingUpdate
    # This will set the Kubernetes container security context
    securityContext:
    # Run the pod under a service account you create.  This is especially useful for OpenShift deployments
    podServiceAccount: bitwarden-sa
  icons:
    # Additional deployment labels
    labels: {}
    # Image name, tag, and pull policy
    image:
      name: ghcr.io/bitwarden/icons
    # The pod resource requirements.  You can adjust these up and down for your environment
    resources:
      requests:
        memory: "64Mi"
        cpu: "50m"
      limits:
        memory: "128Mi"
        cpu: "100m"
    # Specifies the strategy used to replace old Pods by new ones. The value can be "Recreate" or "RollingUpdate". "RollingUpdate" is the default value.
    deploymentStrategy: RollingUpdate
    # This will set the Kubernetes container security context
    securityContext:
    # Run the pod under a service account you create.  This is especially useful for OpenShift deployments
    podServiceAccount: bitwarden-sa
  identity:
    # Additional deployment labels
    labels: {}
    # Image name, tag, and pull policy
    image:
      name: ghcr.io/bitwarden/identity
    # The pod resource requirements.  You can adjust these up and down for your environment
    resources:
      requests:
        memory: "128Mi"
        cpu: "100m"
      limits:
        memory: "256Mi"
        cpu: "200m"
    # Specifies the strategy used to replace old Pods by new ones. The value can be "Recreate" or "RollingUpdate". "RollingUpdate" is the default value.
    deploymentStrategy: RollingUpdate
    # This will set the Kubernetes container security context
    securityContext:
    # Run the pod under a service account you create.  This is especially useful for OpenShift deployments
    podServiceAccount: bitwarden-sa
  notifications:
    # Additional deployment labels
    labels: {}
    # Image name, tag, and pull policy
    image:
      name: ghcr.io/bitwarden/notifications
    # The pod resource requirements.  You can adjust these up and down for your environment
    resources:
      requests:
        memory: "64Mi"
        cpu: "50m"
      limits:
        memory: "128Mi"
        cpu: "100m"
    # Specifies the strategy used to replace old Pods by new ones. The value can be "Recreate" or "RollingUpdate". "RollingUpdate" is the default value.
    deploymentStrategy: RollingUpdate
    # This will set the Kubernetes container security context
    securityContext:
    # Run the pod under a service account you create.  This is especially useful for OpenShift deployments
    podServiceAccount: bitwarden-sa
  scim:
    # SCIM is disabled by default.  To use this service, enable it below and set an appropriate Ingress path
    enabled: false
    # Additional deployment labels
    labels: {}
    # Image name, tag, and pull policy
    image:
      name: ghcr.io/bitwarden/scim
    # The pod resource requirements.  You can adjust these up and down for your environment
    resources:
      requests:
        memory: "64Mi"
        cpu: "50m"
      limits:
        memory: "128Mi"
        cpu: "100m"
    # Specifies the strategy used to replace old Pods by new ones. The value can be "Recreate" or "RollingUpdate". "RollingUpdate" is the default value.
    deploymentStrategy: RollingUpdate
    # This will set the Kubernetes container security context
    securityContext:
    # Run the pod under a service account you create.  This is especially useful for OpenShift deployments
    podServiceAccount: bitwarden-sa
  sso:
    # Additional deployment labels
    labels: {}
    # Image name, tag, and pull policy
    image:
      name: ghcr.io/bitwarden/sso
    # The pod resource requirements.  You can adjust these up and down for your environment
    resources:
      requests:
        memory: "64Mi"
        cpu: "50m"
      limits:
        memory: "128Mi"
        cpu: "100m"
    # Specifies the strategy used to replace old Pods by new ones. The value can be "Recreate" or "RollingUpdate". "RollingUpdate" is the default value.
    deploymentStrategy: RollingUpdate
    # This will set the Kubernetes container security context
    securityContext:
    # Run the pod under a service account you create.  This is especially useful for OpenShift deployments
    podServiceAccount: bitwarden-sa
  web:
    # Additional deployment labels
    labels: {}
    # Image name, tag, and pull policy
    image:
      name: ghcr.io/bitwarden/web
    # The pod resource requirements.  You can adjust these up and down for your environment
    resources:
      requests:
        memory: "64Mi"
        cpu: "50m"
      limits:
        memory: "128Mi"
        cpu: "100m"
    # Specifies the strategy used to replace old Pods by new ones. The value can be "Recreate" or "RollingUpdate". "RollingUpdate" is the default value.
    deploymentStrategy: RollingUpdate
    # This will set the Kubernetes container security context
    securityContext:
    # Run the pod under a service account you create.  This is especially useful for OpenShift deployments
    podServiceAccount: bitwarden-sa
# Images used for jobs and init containers
supportComponents:
  dbMigrator:
    image:
      name: ghcr.io/bitwarden/mssqlmigratorutility
  certGenerator:
    image:
      name: docker.io/nginx
      tag: 1.25.3
  kubectl:
    image:
      name: bitnami/kubectl
      tag: 1.21
# Data volume sizes for shared PVCs
volume:
  dataprotection:
    # Use an existing PVC by specifying the name.
    # existingClaim: claimName
    # Override the accessMode specified in general.volumeAccessMode
    # accessMode: ReadWriteOnce
    # Override the storageClass specified in sharedStorageClassName
    # storageClass: "shared-storage"
    size: "1Gi"
    labels: {}
  attachments:
    # Use an existing PVC by specifying the name.
    # existingClaim: claimName
    # Override the accessMode specified in general.volumeAccessMode
    # accessMode: ReadWriteOnce
    # Override the storageClass specified in sharedStorageClassName
    # storageClass: "shared-storage"
    size: 1Gi
    labels: {}
  licenses:
    # Use an existing PVC by specifying the name.
    # existingClaim: claimName
    # Override the accessMode specified in general.volumeAccessMode
    # accessMode: ReadWriteOnce
    # Override the storageClass specified in sharedStorageClassName
    # storageClass: "shared-storage"
    size: 1Gi
    labels: {}
  logs:
    # Logs are disabled by default
    enabled: false
    # Use an existing PVC by specifying the name.
    # existingClaim: claimName
    # Override the accessMode specified in general.volumeAccessMode
    # accessMode: ReadWriteOnce
    # Override the storageClass specified in sharedStorageClassName
    # storageClass: "shared-storage"
    size: 1Gi
    labels: {}
  caCertificates:
    # Extra root certificates are disabled by default
    enabled: false
    # Load custom Certificates from the following ConfigMap
    configMapName: cacert

#
# Configure service account for pre- and post-install hooks
#
serviceAccount:
  name: service-account
  # Certain instances will prequire the creation of a pre-deployed service account.  For instance, AWS IAM enabled service accounts need to be created outside
  # of the chart to allow for setting of permissions on other AWS services like Secrets Manager
  deployRolesOnly: false

#
# Configure database
#
database:
  # deploy the database pod?  if false, a connection string to a SQL Server will need to be provided through one of the configuration providers.
  enabled: true
  # Labels to add to the MSSQL deployment
  labels: {}
  # Image name, tag, and pull policy
  image:
    name: mcr.microsoft.com/mssql/server
    # Tag of the image to use. (Defaults to general.coreVersion)
    tag: 2022-CU11-ubuntu-22.04
  # The container is limited to the resources below.  Adjust for your environment.
  resources:
    requests:
      memory: "2G"
      cpu: "100m"
    limits:
      memory: "2G"
      cpu: "500m"

  # The MSSQL volumes for the PVCs
  volume:
    backups:
      # Use an existing PVC by specifying the name.
      # existingClaim: claimName
      # Override the accessMode specified in general.volumeAccessMode
      # accessMode: ReadWriteOnce
      # Override the storageClass specified in sharedStorageClassName
      # storageClass: "shared-storage"
      size: 1Gi
      labels: {}
    data:
      # Use an existing PVC by specifying the name.
      # existingClaim: claimName
      # Override the accessMode specified in general.volumeAccessMode
      # accessMode: ReadWriteOnce
      # Override the storageClass specified in sharedStorageClassName
      # storageClass: "shared-storage"
      size: 10Gi
      labels: {}
    log:
      # Use an existing PVC by specifying the name.
      # existingClaim: claimName
      # Override the accessMode specified in general.volumeAccessMode
      # accessMode: ReadWriteOnce
      # Override the storageClass specified in sharedStorageClassName
      # storageClass: "shared-storage"
      size: 10Gi
      labels: {}
  # Specifies the strategy used to replace old Pods by new ones. The value can be "OnDelete" or "RollingUpdate". "OnDelete" is the default value.
  # When set to OnDelete, the SQL pod will not be recreated automatically on update.  It must be manually deleted to update.
  updateStrategy: OnDelete
  # This will set the Kubernetes container security context
  securityContext:
  # Run the pod under a service account you create.  This is especially useful for OpenShift deployments
  podServiceAccount: bitwarden-sa

# You can specify raw Kubernetes manifests that will be applied before or after the base Helm install.
# Please see the chart README in GitHub for more information and examples.
rawManifests:
  preInstall: []
  # E.g. add a custom certificate to your bitwarden installation.
  # - apiVersion: v1
  #   kind: ConfigMap
  #   metadata:
  #     name: cacert
  #   data:
  #     rootca.crt: |
  #       -----BEGIN CERTIFICATE-----
  #       xxxx
  #       -----END CERTIFICATE-----
  postInstall: []
```
